# **Metode Naive Bayes**
## **TUGAS 5**

**METODE NAIVE BAYES**

Naive Bayes adalah algoritma machine learning untuk masalah klasifikasi. Ini didasarkan pada teorema probabilitas Bayes. Hal ini digunakan untuk klasifikasi teks yang melibatkan set data pelatihan dimensi tinggi. Beberapa contohnya adalah penyaringan spam, analisis sentimental, dan klasifikasi artikel berita.

Algoritma Naive Bayes adalah teknik klasifikasi berdasarkan penerapan teorema Bayes

dengan asumsi kuat bahwa semua prediktor independen satu sama lain. Secara sederhana dengan kata lain, asumsinya adalah bahwa kehadiran fitur di kelas tidak tergantung pada kehadiran fitur lain di kelas yang sama.

**Pemodelan dengan Naive Bayes**

Library Python, Scikit learn adalah library paling berguna yang membantu untuk membangun Naive Bayes model dengan Python. Berikut adalah tiga jenis model Naive Bayes di bawah Scikit library Python:

a. Gaussian Naive Bayes

Ini adalah pengklasifikasi Naive Bayes paling sederhana yang memiliki asumsi bahwa data dari masing-masing label diambil dari distribusi Gaussian sederhana.

b. Multinomial Naive Bayes

Pengklasifikasi Naive Bayes lain yang berguna adalah Multinomial Naive Bayes di mana fitur-fiturnya adalah diasumsikan diambil dari distribusi Multinomial sederhana. Naive Bayes semacam itu adalah paling sesuai untuk fitur yang mewakili jumlah diskrit.

c. Bernoulli Naive Bayes

Model penting lainnya adalah Bernoulli Naive Bayes di mana fitur diasumsikan biner (0s dan 1s). Klasifikasi teks dengan model 'bag of words' dapat menjadi aplikasi dari Bernoulli Naive Bayes.



**Kelebihan dan Kekurangan**

Berikut ini adalah beberapa kelebihan menggunakan pengklasifikasi Naive Bayes:

- Klasifikasi Naive Bayes mudah diimplementasikan dan cepat.
- Ini akan menyatu lebih cepat daripada model diskriminatif seperti regresi logistik.
- Membutuhkan lebih sedikit data pelatihan.
- Sifatnya sangat skalabel, atau skalanya linier dengan jumlah prediktor dan titik data.
- Dapat membuat prediksi probabilistik dan dapat menangani kontinu beserta diskrit data.
- Algoritma klasifikasi Naive Bayes dapat digunakan untuk biner maupun multi-kelas masalah klasifikasi keduanya.


Berikut ini adalah beberapa kekurangan dari penggunaan pengklasifikasi Naive Bayes:

- Salah satu Kelemahan terpenting dari klasifikasi Naive Bayes adalah fiturnya yang kuat kemandirian karena dalam kehidupan nyata hampir tidak mungkin untuk memiliki seperangkat fitur yang benar-benar independen satu sama lain. 
- Masalah lain dengan klasifikasi Naive Bayes adalah 'frekuensi nol' yang berarti bahwa jika variabel kategori memiliki kategori tetapi tidak diamati dalam data pelatihan set, maka model Naive Bayes akan menetapkan probabilitas nol untuk itu dan itu tidak akan dapat untuk membuat prediksi

## NAIVE BAYES

**Persiapan Lingkungan**



Impor KNeighborsClassifier dari sklearn

Impor pandas library

In [ ]:
# Import train_test_split dari sklearn

from sklearn.model_selection import train_test_split 
#split dataset into train and test data

In [ ]:
# Import pandas library

import pandas as pd
import numpy as np

In [ ]:
# library for Naive Bayes Gaussian
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.preprocessing import LabelEncoder

#Model Select
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning, append=True)

In [ ]:
dataset_url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"

In [ ]:
df = pd.read_csv(dataset_url)
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
#check number of rows and columns in dataset
df.shape

(150, 5)

**Hitung Data**

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
X=iris.data
y=iris.target

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
#create a dataframe with all training data except the target column
X = df.drop(columns=["variety"])#check that the target variable has been removed
X.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
# percent_amount_of_test_data = / HUNDRED_PERCENT
percent_amount_of_test_data = 0.3

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = percent_amount_of_test_data, random_state=0)

In [ ]:
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [ ]:
# classifier
gaussian = GaussianNB()
# 
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_random_Forest : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
accuracy_Naive Bayes: 1.000
precision_Naive Bayes: 1.000
recall_Naive Bayes: 1.000
f1-score_random_Forest : 1.000


In [ ]:
# separate target 

# values
X=df.iloc[:,0:4].values

# classes
y=df.iloc[:,4].values

In [ ]:
clf = GaussianNB()
clf.fit(X, y)
clf_pf = GaussianNB()
clf_pf.partial_fit(X, y, np.unique(y))

GaussianNB()

In [ ]:
# try with value [5.5, 3, 5, 2.2]
print(clf_pf.predict([[5.5, 3, 5, 2.2]]))

['Virginica']


In [ ]:
# try with value [5.5, 3, 5, 2.2]
print(clf_pf.predict([[4, 3, 5, 1.2]]))

['Versicolor']
